### ISSUE TITLE
[Feature] Update the layout of the website to match with existing CC websites

### ISSUE THREAD

**Issue by tripathics** [creativecommons/cc-resource-archive#123] opened 2023-03-28 20:46 UTC
## Description
Update **layout** of the whole website to match the design of other creative commons websites i.e. Navigation bar and Footer need to be updated.

## Alternatives
**Update Navigation bar:**
* Add links for submitting new resources and viewing all resources.
* Update the CC logo to include "Resource Archive" instead of "Creative Commons" as this should be availble after adding the expanding menu on Nav bar #68.

**Add a Footer component:**
* Adding a footer like the ones existing on other CC websites

## Additional context
For reference, the navigation bar and footer to be implemented can be viewed on [CC global summit](https://summit.creativecommons.org/) and [CC open source](https://opensource.creativecommons.org/)

## Implementation
- [X] I would be interested in implementing this feature.

**Comment by adidevs** [comment] 2023-03-30 16:27
Hey @tripathics ,while the issue you have put forward here is legitimate, it is not to the point and the title rather vague and should be updated to target a specific problem which what I can deduce is adding a navigation bar and a footer. However there are already issues present for the same and are duplicated. For example, the Navigation bar has been covered in issues #94 and #107 and the footer has been covered in issues #65 and #34.

Thus i suggest you close this issue and move the conversation to those issues and solve them from there to avoid duplication. Cheers!

**Closed** 2023-03-31 20:18 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code

**Comment by possumbilities** [comment] 2023-03-31 20:21
Also likley a duplicate of #72
