### ISSUE TITLE
[Bug] Clicking on empty area redirecting to "https://creativecommons.org/"

### ISSUE THREAD

**Issue by Akshaybagai52** [creativecommons/cc-resource-archive#185] opened 2024-02-23 17:31 UTC
## Description
When clicking on empty area specifically area align with the logo is redirecting to "https://creativecommons.org/" i.e. clicking on empty area triggering the href on logo

## Reproduction

1. Go to this link :- https://resources.creativecommons.org/
2. hover on area right of logo
3. then click on the area 
4. You can see that it is redirecting to the "https://creativecommons.org/"

## Expectation
The  area should not clickable

https://github.com/creativecommons/cc-resource-archive/assets/100753870/d4d26c7b-dfd1-4f97-9030-33aef7edfc30

## Screenshots
![image](https://github.com/creativecommons/cc-resource-archive/assets/100753870/8bfd359f-70c4-4f57-a097-5278001dda47)

## Environment

 - Device: laptop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 121.0.6167.187

## Additional context
I would love to contribute on this issue

**Comment by Xaid-vfx** [comment] 2024-02-23 18:51
Hey @Akshaybagai52 , 
Appreciate the efforts and enthusiasm, but issue #70 talks about this and PR #145 resolves this. 
You can provide your input there if you have something to add.

**Comment by Akshaybagai52** [comment] 2024-02-24 06:51
Hello @Xaid-vfx 
Thanks for your response. does all the bugs related to ui are fixed already because i'm seeing that right now in the live site

**Comment by Akshaybagai52** [comment] 2024-02-24 06:53
@Xaid-vfx As you can see in this screenshot that logo is not good and then language section in resources also going rightwards in mobile design 
![image](https://github.com/creativecommons/cc-resource-archive/assets/100753870/d6cccd49-7d4c-4e29-951e-8220c5893031)

**Comment by Xaid-vfx** [comment] 2024-02-24 09:51
@Akshaybagai52  You are seeing the logo issue on live site because the PR #145 is not merged yet. 

But you are free to raise more issues, just make sure that there is no existing issue that points out the same problem.

**Comment by BalrajDhakad** [comment] 2024-02-24 15:25
Hey,
I am willing to work on this issue

**Comment by PhantomPhreak007** [comment] 2024-03-01 14:19
hello community , I have understood  the issue and I am working on it.

**Comment by PhantomPhreak007** [comment] 2024-03-01 14:22
can anybody please tell me on which folder should I work on to fix this issue.

**Comment by Murdock9803** [comment] 2024-03-01 15:00
@PhantomPhreak007 This issue has not yet received the `status : ready for work` label, so it cannot be assigned to work upon.
moreover, a similar issue #70 focuses on this problem. You can refer to that for more context. 
Good luck and happy contributing !

**Comment by possumbilities** [comment] 2024-03-01 15:15
I'm closing this since it's a duplicate of #70

**Closed by possumbilities** 2024-03-01 15:15 UTC
Labels: 🟧 priority: high, 🚦 status: awaiting triage, 🛠 goal: fix, 💻 aspect: code
