### ISSUE TITLE
[Bug] The topic list div covers the cards below it

### ISSUE THREAD

**Issue by adityakm24** [creativecommons/cc-resource-archive#116] opened 2023-03-26 05:41 UTC
## Description
The div which contains the topic, medium, and language list in the all.html file covers/flows on top of the thumbnail box below them.
![before1 2](https://user-images.githubusercontent.com/38864621/227757239-bbb946f0-eb03-40dc-beaa-5982ce86427c.png)

## Reproduction

1. visit the link on a laptop: https://resources.creativecommons.org/all/?

## Expectation
The site is expected to adjust the positioning and sizing of elements according to screen size for better accessibility.
The issue arises because the list div overlaps the cards, leading to accessibility issues. One of the critical problems with the current CSS properties is that the list div overlaps the cards on different screen sizes, causing a poor user experience. To resolve this issue, we can implement responsive design techniques with CSS styling to add some space between the cards and the elements above them. This will ensure that the list div does not overlap the cards 

## Environment

 - Device: Laptop
 - OS: op!_ OS 21.10
 - Browser: Chrome
 - Version: Version 111.0.5563.64 (Official Build) (64-bit)
 - Other info: display resolution: 1920 x 1080 

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Lakshay-Pruthi** [comment] 2023-03-26 07:16
I am not able to reproduce this on my PC. Could you try hard reloading the page? and see if the error still exists. 
![image](https://user-images.githubusercontent.com/91469717/227760842-59a56033-9a6f-41d1-986e-854293aa7bca.png)

**Comment by Xaid-vfx** [comment] 2023-03-26 08:00
@adityakm24 I am not able to produce this error as well. Could you provide more details?

**Comment by adityakm24** [comment] 2023-03-26 10:05
I just tried it using my laptop running OS: op!_ OS 21.10 and in incognito mode using chrome. The issue still persists

**Comment by Xaid-vfx** [comment] 2023-03-26 10:58
@adityakm24 Chrome incognito mode with the same dimensions.

<img width="918" alt="Screenshot 2023-03-26 at 4 21 32 PM" src="https://user-images.githubusercontent.com/77684943/227770912-7af4ac92-09b7-4808-a554-c431eec347b8.png">

I have adjusted and tried all dimensions but wasn't able to reproduce. I think the bug only exists on your machine which is weird. Could you check the website in a different browser? Maybe firefox?

**Comment by Lakshay-Pruthi** [comment] 2023-03-26 11:04
@Xaid-vfx Same here.
@adityakm24 Could you share a screen recording for this, following these steps -->
1. Load the https://resources.creativecommons.org/  page.
2. Click on See all.
3. See if there is any error in the console.

**Comment by possumbilities** [comment] 2023-03-31 19:35
I haven't been able to reproduce either, yet. Marking as `work required` just in case it is occuring.

**Comment by yogeyyy** [comment] 2024-03-14 06:55
Hello @possumbilities , 

Since `Submit a resource`  link is added, there is enough space and padding between the cards and the filter links. I could not reproduce this issue as well. Lemme know your thoughts.

**Comment by possumbilities** [comment] 2024-09-17 13:11
This should be resolved with the new Vocabulary implementation now.

**Closed by possumbilities** 2024-09-17 13:11 UTC
Labels: 🟧 priority: high, 🧹 status: ticket work required, 🛠 goal: fix, 💻 aspect: code
