### ISSUE TITLE
Make the landing page responsive

### ISSUE THREAD

**Issue by tinniaru3005** [creativecommons/cc-resource-archive#26] opened 2023-02-24 00:20 UTC
## Description

The landing page is not responsive and doesn't look good on all kinds of devices. This affects the accessibility of the website.

## Reproduction

The task can be broken down into working on the responsiveness of 3 parts:
- navbar
- resourcenavbar
- thumbnaillist
This can be done in several ways like:
- use of flexbox and grids
- avoiding the use of fixed widths for all devices
- Use flexible typography by using relative units like ems or rems to set font sizes. This approach ensures that the text scales proportionally with the device's screen size, making it easier to read on smaller screens.

## Expectation

 Improve the look and feel of a website, enhance the user experience across all devices

## Screenshots

![whole](https://user-images.githubusercontent.com/62856848/221061146-aa6671ac-30d3-46fe-8825-3154b3b3191a.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Keerthivardhan1** [comment] 2023-02-27 09:53
I have been working with frontend web tech stacks since past few months .  This issue suits me a lot can I  works on this issue

**Comment by Keerthivardhan1** [comment] 2023-02-27 11:01
I am trying to solve the issue--- Make the landing page responsive
so i tried to set up the project in my mechine and goon through the following steps
1.forked and cloned the project
2.installed [Ruby+Devkit 3.1.3-1 (x64)](https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.1.3-3.1/rubyinstaller-devkit-3.1.3-1-x64.exe) and completed setup
4.installed MSYS2 and MINGW development tool chain
5. I had run this command in the command prompt gem install jekyll bundler
but when I am running the file--- resources.html it was not showing proper results
please help me and let me know if I have done any thing wrong --
 OS :- windows 11 (edited)
<img width="239" alt="pro" src="https://user-images.githubusercontent.com/110013820/221546431-0b9e12c0-cc4f-433a-affe-0fe8ca85d57a.png">
<img width="919" alt="showing" src="https://user-images.githubusercontent.com/110013820/221546432-84ae2fd3-42d9-4c84-a985-366d77605e37.png">

**Comment by tinniaru3005** [comment] 2023-02-27 11:14
Hey @Keerthivardhan1 the issue is not yet approved. Please wait for any issue to get approved before you start working. Also I have mentioned in the issue that I would like to take it up. You can raise an issue and wait for it to get approved and then start working or you can ask for an issue in which the author has not expressed interest in taking in up by checking the checkbox. I also suggest you to go through the Contributing Guidelines. It will clear all your doubts and help you get started with contributing.

**Comment by tinniaru3005** [comment] 2023-02-27 11:16
Also I work on Linux, so I cannot help you much in setting up the project. But you can definitely ask for help in the Slack channel and someone will surely help you out. 💜

**Comment by Keerthivardhan1** [comment] 2023-02-27 11:21
thank you @tinniaru3005

**Comment by KrownWealth** [comment] 2023-04-03 16:01
I loved the way you break down the reproduction @tinniaru3005. If the issue is later approved. I will be glad to help with one or two of the reproduction.

**Comment by Keerthivardhan1** [comment] 2023-04-04 08:25
Thank you, @possumbilities, for including me in this Issue.
@tinniaru3005 I am exited to work with you on this issue . because I had already done some work on this issue.

**Comment by Keerthivardhan1** [comment] 2023-04-04 08:56
## For mobile devices, the thumbnail boxes are displayed sequentially, one after the other, as shown in the following image:

<img width="381" alt="thumbnailbox" src="https://user-images.githubusercontent.com/110013820/229739791-64774316-b1b1-49a7-a204-61dc73e89f90.png">

# On click or Hover
<img width="362" alt="thunmnailboxhover" src="https://user-images.githubusercontent.com/110013820/229739834-21932380-9a78-4fbb-b792-105d3edc0a07.png">

## Please feel free to provide any suggestions.

**Comment by KrownWealth** [comment] 2023-04-04 09:15
@Keerthivardhan1 this looks great, but I would want you to consider design pattern for the desktop, as the thumnail image should allign with the card without a space on the left and right.

**Comment by Keerthivardhan1** [comment] 2023-04-10 18:45
@KrownWealth, Thanks for your suggestion I will definitely consider it. I will be back with in 1 day with possible design patterns.
Sorry for the late.

**Comment by Keerthivardhan1** [comment] 2023-04-19 14:06
Regarding Thumbnails @tinniaru3005 had already raised one PR.

**Comment by tinniaru3005** [comment] 2023-04-20 12:35
> Regarding Thumbnails @tinniaru3005 had already raised one PR.

Hey, I guess have raised a PR adding a tags section to filter resources and not regarding thumbnails. Can you please confirm which PR you are referring to?

**Comment by Keerthivardhan1** [comment] 2023-04-21 18:13
https://github.com/creativecommons/cc-resource-archive/pull/29
but as you submitted before labeling ready to work on the issue so, @possumbilities closed this PR.

**Comment by BalrajDhakad** [comment] 2024-02-24 13:38
Is this issue still open,
 I am willing to contribute to this issue,
can you please guide me to the first step

**Comment by Murdock9803** [comment] 2024-03-11 01:46
I made the `resourcenavbar`  section responsive in PR #204 🙌 
will work on the rest too, section by section

**Comment by Murdock9803** [comment] 2024-03-22 13:47
I have worked on the middle section, i.e. `Resource-navbar` section in my PR #236

**Closed** 2024-03-22 21:43 UTC
Labels: 🟨 priority: medium, 🏁 status: ready for work, 🛠 goal: fix, 💻 aspect: code
