### ISSUE TITLE
[Bug] Footer not displayed appropriately in the website on large screens

### ISSUE THREAD

**Issue by Queen-codes** [creativecommons/cc-resource-archive#330] opened 2024-10-04 13:32 UTC
## Description
On large screens at 2560px, the footer is not displayed at the bottom of the page.

## Reproduction

1. Open the website.
2. Resize the browser using developer tools or view it on different screens and then try clicking on various filters that just one or no resources matching.
3.  The footer's position on a large screen from 2560px varies, sometimes appearing in the middle of the page instead of the bottom.
4. See error.

## Expectation
I expected the footer to be fixed at the bottom of the page, regardless of the viewport size.

## Screenshots
<img width="755" alt="Screenshot 2024-10-04 at 12 44 01" src="https://github.com/user-attachments/assets/1d291048-831e-4056-9ebe-4b769d676ceb">

## Resolution

- [] I would be interested in resolving this bug.

**Comment by possumbilities** [comment] 2024-10-07 14:05
The footer appears at the bottom of the webpage, not the bottom of the window. This looks like the intended behavior of the Vocabulary system.

Closing as it appears to be expected behavior for Vocabulary.

**Closed by possumbilities** 2024-10-07 14:05 UTC
Labels: 🟧 priority: high, 🚦 status: awaiting triage, 🛠 goal: fix, 💻 aspect: code

**Comment by Queen-codes** [comment] 2024-10-07 17:51
thank you @possumbilities this helped improve my understanding and expected behaviour of the design system.
