### ISSUE TITLE
[Feature] Improving the individual resource pages

### ISSUE THREAD

**Issue by vanichitkara** [creativecommons/cc-resource-archive#45] opened 2023-02-27 09:17 UTC
## Problem
Currently, the resource pages don't have a good UI and UX. The improved resource page will facilitate easy download and preview of the resources in different languages.

## Description
The individual resource page, like the one in the image doesn't show PDF preview before downloading, which is a useful feature in case a person can't download a resource due to storage limitations. 

![Screenshot (203)](https://user-images.githubusercontent.com/64951124/221522375-0a63497a-cd51-47ad-be64-21a7bb70e597.png)

## Alternatives
I have considered a few solutions to improve the page's overall UI and UX.
* Adding a PDF preview for the ease of access
* Adding download button and repository button on the top
* Adding a dropdown button to access the resource in different langugaes
* Adding a toggle button to download the resource as a flat pager or folded pager

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by C-NikhilKarthik** [comment] 2023-02-27 09:48
Hello @vanichitkara i have already raised this issue yesterday. You can look up more issues

**Comment by vanichitkara** [comment] 2023-02-27 09:50
@C-NikhilKarthik, I have raised this issue since I had more ideas to implement after seeing your issue. But, well, I'll look up for something else too.

**Comment by possumbilities** [comment] 2023-03-31 20:05
duplicate of #41 closing.

**Closed by possumbilities** 2023-03-31 20:05 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code
