### ISSUE TITLE
[Feature] Add a new resource

### ISSUE THREAD

**Issue by nown1ne** [creativecommons/cc-resource-archive#86] opened 2023-03-16 17:54 UTC
## Problem
Add a presentation explaining copyright and creative commons.

## Description
While reading through the style guide I came across a really well made presentation explaining everything about copyright and creative commons made in canva. I think that this should be added as a resource and should also be in the featured Top 16.

![image](https://user-images.githubusercontent.com/25835195/225709229-a2f5203d-02ea-41de-80a7-c9a27ba02ef9.png)
## Additional context
Here is the link to the presentation being discussed
[Canva Link](https://www.canva.com/design/DADm40hSwIU/9yEhtLnl5O1WMKbx8JSSkA/watch?utm_content=DADm40hSwIU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment] 2023-03-20 20:28
Duplicate of #85 I'd suggest moving any information or conversations there.

**Comment by nown1ne** [comment] 2023-03-21 19:00
@possumbilities 

I wanted to bring to your attention that this issue is a request to add a new resource to the archive website for people to better understand copyright and learn how creative commons works. 
This is only about requesting to add a newly found resource to the archive and thus create a new post/resource.

Issue #85 on the other hand is about a bug where the link to add resource (the one that leads to google form) is missing when all resources are being shown i.e [On this particular location](https://resources.creativecommons.org/all/)
![image](https://user-images.githubusercontent.com/25835195/226713621-28bd4c05-0289-4cbc-8a5b-ec54ec976fb0.png)

**Comment by possumbilities** [comment] 2023-03-21 20:15
@nown1ne You're right, reopening. Sorry!

**Closed** 2024-03-22 21:32 UTC
Labels: 🟩 priority: low, 🏁 status: ready for work, ✨ goal: improvement, 💻 aspect: code

**Comment by possumbilities** [comment] 2024-03-26 14:34
@praveen-rikhari If you comment here I can credit you!

**Comment by praveen-rikhari** [comment] 2024-03-26 14:40
Thank you @possumbilities
