### ISSUE TITLE
[Bug] broken links on the resources website

### ISSUE THREAD

**Issue by ohneEigenschaften** [creativecommons/cc-resource-archive#11] opened 2022-08-29 19:46 UTC
## Description
There are several links that are broken on resources.creativecommons.org

## Reproduction
You can see some of the broken links by viewing the following pages "Get CC Savvy (https://resources.creativecommons.org/get-cc-savvy/)," "Creative Commons Kiwi (https://resources.creativecommons.org/creative-commons-kiwi/)," "CC Licenses Poster (https://resources.creativecommons.org/cc-licenses-poster/ -- the linked page still exists but a readable image is no longer there)," or "Creative Commons licenses for nonprofits (https://resources.creativecommons.org/creative-commons-licenses-for-nonprofit-organizations/)." This is not an exhaustive list of all the broken links on resources.creativecommons.org. 

## Expectation
Delete the pages with broken links, or provide working links. 

## Resolution
- [ ] I would be interested in resolving this bug.

**Comment by tusharbansal22** [comment] 2023-02-23 11:52
#14 Made some changes. Please check

**Comment by Keerthivardhan1** [comment] 2023-02-27 09:50
<img width="754" alt="cc" src="https://user-images.githubusercontent.com/110013820/221529377-32be4ef2-00a7-4317-8b50-13aafa573e8d.png">
This are all the broken links that I found.
and almost all of them are showing 404 error 
this means server can not find the resources mentioned.
please let me know if I am wrong
can I proceed with this issue  thank you

**Comment by possumbilities** [comment] 2023-03-01 19:12
@Keerthivardhan1 And a tremendous thank you for looking into this further! ❤️  

I would also strongly encourage you to provide the full list of broken links as actual text here in a comment (you can use Markdown tables or just a bulleted list to do so). That way it's more accessible, and easier for people to document and check for. 



I'm marking this as `ticket work required` which means it's not yet ready for PRs. It'll move to `ready for work` when the documentation here is more clear and thorough. 

Thanks all so far for your contributions!

**Comment by Keerthivardhan1** [comment] 2023-03-01 19:49
Thanks @possumbilities , sure I will provide list of all the broken links in text format.
Before I do not know that this king of issue already exist in the repo.
 so I had created the  issue :- https://github.com/creativecommons/cc-resource-archive/issues/46 regarding all the broken links and posted the progress can you one consider it please. thank you once again

**Comment by possumbilities** [comment] 2023-03-01 19:53
@Keerthivardhan1 Ah, thanks for linking to that other issue. For the future make sure what you are submitting as an Issue doesn't already exist, and if it does then I'd suggest adding onto that Issue instead of creating a new one :)

Once you've got all the details moved in here I'll close that other one as a duplicate of this one.

**Comment by Keerthivardhan1** [comment] 2023-03-01 20:00
ok , I am on it .

**Comment by Keerthivardhan1** [comment] 2023-03-01 20:28
## About the tool that I used to find all the broken links
There is a tool called brokenlinkchecker :-https://www.brokenlinkcheck.com/
hear we can find all the broken links in out site. 
To Reproduce the same results (finding all the broken links ):
1. visit the site :- https://www.brokenlinkcheck.com/
2. enter the url the site without any subfolders that is ( /'s ) 
3. click on find broken links 
4. you will find all the broken links . 

## List Of All Broken Links 

Hear in the site https://resources.creativecommons.org/ following are the broken links :-
 -----BROKEN LINK------- along with Page Where it Found :- ----------
                                                                                                                                                                                                       
1. https://docs.google.com/forms/d/1EmxeeHj1q27ODP6XPZHyRHxEIyNYW2JLU1_DCV6Edm8/viewform?embedded=true
         In the page :- https://resources.creativecommons.org/submit/
2. https://layervault.com/creative-commons/Six%20Licenses%20guide
           In the page :- https://resources.creativecommons.org/six-licenses-for-sharing-your-work/

3. https://layervault.com/creative-commons/Public%20Domain%20guide 
          In the page :- https://resources.creativecommons.org/guide-to-using-public-domain-tools/

4. http://wiki.creativecommons.org/images/6/6d/6licenses-flat.pdf%20property=
        In the page :-https://resources.creativecommons.org/six-licenses-for-sharing-your-work/ 

6. http://dotsub.com/view/fbdc3bd1-d1c2-4b63-be02-4fcb66aac443
        In the page :- https://resources.creativecommons.org/wanna-work-together/

7. http://wiki.creativecommons.org/images/8/88/Publicdomain.pdf%20property=
        In the page :- https://resources.creativecommons.org/guide-to-using-public-domain-tools/

8. https://player.vimeo.com/video/25684782
        In the page :- https://resources.creativecommons.org/creative-commons-kiwi/

9. http://vimeo.com/25684782
        In the page :- https://resources.creativecommons.org/creative-commons-kiwi/

10. http://vimeo.com/ccanz
        In the page :- https://resources.creativecommons.org/creative-commons-kiwi/

11. https://p2pu.org/he/groups/get-cc-savvy/
        In the page :- https://resources.creativecommons.org/get-cc-savvy/

12. https://layervault.com/creative-commons/cc%20poland%20poster
        In the page :- https://resources.creativecommons.org/cc-licenses-poster/

13. http://oerpolicy.eu/postcard-from-the-oer-workshop-in-porto/
        In the page :- https://resources.creativecommons.org/oer-whats-in-it-for-me/

14. https://player.vimeo.com/video/84880520
        In the page :- https://resources.creativecommons.org/creative-commons-licenses-for-nonprofit-organizations/

15. http://vimeo.com/84880520
        In the page :- https://resources.creativecommons.org/creative-commons-licenses-for-nonprofit-organizations/

16. https://layervault.com/creative-commons/Foter%20Creative%20Commons%20infographic
        In the page :- https://resources.creativecommons.org/how-to-attribute-creative-commons-photos/

17. http://creativecommons.cashmusic.org/
        In the page :- https://resources.creativecommons.org/cash-music-creative-commons-portal/


for more clarity 
 I'd suggest you to visit the site :- https://www.brokenlinkcheck.com/ 
and follow the process explained at the beginning. 
Thank You. .

**Comment by Keerthivardhan1** [comment] 2023-03-02 12:35
"Visit" link in https://resources.creativecommons.org/cash-music-creative-commons-portal/
is leading to bad host server error. 
Can you give me a clarity that is this the destination page of that link 
<img width="878" alt="badhost" src="https://user-images.githubusercontent.com/110013820/222066122-9a3bb85a-1e6d-4270-9676-b6f17ff17460.png">

if yes 
the problem is that , the url of the destination page had been updated
solution :
we must update the url of destination page in our code base as well 
thank you

**Comment by possumbilities** [comment] 2023-03-03 21:13
@Keerthivardhan1 Well done on listing them out! I think next steps might be helpful in determining what the correct links _should_ be corresponding to the ones that are presently broken, so there's a solid map on which ones we can change, and which ones we may need it discuss removing entirely.

As for the cash music portal I'm not sure on what the correct link is, I will look into it and see if I can track down something. You could also look back through the repository history here and see if you can discern any clarity, that may or may not work.

**Comment by Keerthivardhan1** [comment] 2023-03-04 04:54
sure @possumbilities

**Comment by Keerthivardhan1** [comment] 2023-03-08 20:44
on researching 
<img width="676" alt="ifound" src="https://user-images.githubusercontent.com/110013820/223843297-5a18a20e-82b1-49cf-99aa-4f1f4de1a381.png">
that mentioned link takes to the same destination and the result is the same.
but by this article I think the destination page might be this :- https://cashmusic.org/

**Comment by Keerthivardhan1** [comment] 2023-03-08 20:52
About 
15.    https://layervault.com/creative-commons/Foter%20Creative%20Commons%20infographic
In the page :- https://resources.creativecommons.org/how-to-attribute-creative-commons-photos/

Error shown :- 404 
even there is no rout link https://layervault.com/creative-commons
and more over the link link [layervault.com ](https://layervault.com)
<img width="807" alt="shown" src="https://user-images.githubusercontent.com/110013820/223846964-d73c1fa5-b297-4991-8b63-a4fda1d6e01f.png">
takes as to the single page site and is has no links nothing just a text and background img 

even there is no rout like

**Comment by Keerthivardhan1** [comment] 2023-03-10 17:19
I would like to work on this issue can you please assign to me.

**Comment by possumbilities** [comment] 2023-03-10 20:25
@Keerthivardhan1 for the cashmusic bit. have you tried using the Internet Archive to see if the two sites/services are the same?

**Comment by Keerthivardhan1** [comment] 2023-03-10 20:36
no @possumbilities. thanks a lot for the idea.

**Comment by Keerthivardhan1** [comment] 2023-03-10 21:08
creativecommons.cashmusic.org sit maps to following one 
https://web.archive.org/web/20160309043535/http://creativecommons.cashmusic.org/  
 
cashmusic :- [cashmusic.org](https://cashmusic.org/)

what i found is that UI of both sites are different   *But twitter account of the both sites point to the same one  

in Internet Archive
<img width="554" alt="ia" src="https://user-images.githubusercontent.com/110013820/224428035-ced14225-7b05-4906-9e37-0a65c9979617.png">


 in [cashmusic.org](https://cashmusic.org/) site
<img width="521" alt="sameia" src="https://user-images.githubusercontent.com/110013820/224428053-2eb6ba12-9abc-4217-aba8-ca0e5b2197b5.png">

so I think 
They had updated there site url and UI . 
but url in our site is not updated accordingly this is the reason we are facing 404 error.

I am new to internet archives . it will be helpful if you once verify it . thanks.

**Comment by Keerthivardhan1** [comment] 2023-03-11 09:29
in 15 :-  more over in browser it is showing  http://www.layervault.com/  not secure

**Comment by Keerthivardhan1** [comment] 2023-03-13 14:44
https://github.com/creativecommons/cc-resource-archive/issues/11#issuecomment-1450803514

as far as my research.

the website "layervault.com" no longer exists and there is no updated URL available. It seems that the website has been discontinued and the content has been taken down. 
so the following links 

https://layervault.com/creative-commons/Six%20Licenses%20guide
In the page :- https://resources.creativecommons.org/six-licenses-for-sharing-your-work/

https://layervault.com/creative-commons/Public%20Domain%20guide
In the page :- https://resources.creativecommons.org/guide-to-using-public-domain-tools/

http://wiki.creativecommons.org/images/6/6d/6licenses-flat.pdf%20property=
In the page :-https://resources.creativecommons.org/six-licenses-for-sharing-your-work/

https://layervault.com/creative-commons/cc%20poland%20poster
In the page :- https://resources.creativecommons.org/cc-licenses-poster/

https://layervault.com/creative-commons/Foter%20Creative%20Commons%20infographic
In the page :- https://resources.creativecommons.org/how-to-attribute-creative-commons-photos/

http://wiki.creativecommons.org/images/8/88/Publicdomain.pdf%20property=
In the page :- https://resources.creativecommons.org/guide-to-using-public-domain-tools/

need to be deleted or 
we have to ask for maintainers or contributor who have added this that if the resource really exists now ?

on the way I found this artical.  says([BrokerMarket Acquires LayerVault IP](https://layervault.tumblr.com/post/135321660939/brokermarket-acquires-layervault-ip))
----->https://layervault.tumblr.com/

For videos related issue or links they are pointing to vimeo.com website following are the reasons :- 
1 . lake of permissions for the users to access the content
2. for some videos the users need to be logged in to access that content

following are the related links in the website

https://player.vimeo.com/video/25684782
In the page :- https://resources.creativecommons.org/creative-commons-kiwi/

http://vimeo.com/25684782
In the page :- https://resources.creativecommons.org/creative-commons-kiwi/

http://vimeo.com/ccanz
In the page :- https://resources.creativecommons.org/creative-commons-kiwi/

for above three user need to be logged in to access content

https://player.vimeo.com/video/84880520
In the page :- https://resources.creativecommons.org/creative-commons-licenses-for-nonprofit-organizations/

http://vimeo.com/84880520
In the page :- https://resources.creativecommons.org/creative-commons-licenses-for-nonprofit-organizations/

and bellow video is deleted by website owner. 
http://dotsub.com/view/fbdc3bd1-d1c2-4b63-be02-4fcb66aac443
In the page :- https://resources.creativecommons.org/wanna-work-together/

please let me know if Iam wrong. Thank you @possumbilities.

**Comment by Keerthivardhan1** [comment] 2023-03-13 14:53
@possumbilities can you please review this issue (decent amount of work is done on it)
https://github.com/creativecommons/cc-resource-archive/issues/50 . thanks a lot for your time.

**Comment by possumbilities** [comment] 2023-03-15 20:54
@Keerthivardhan1 Hi, and thank you for all the work here!  For any places like layervault that seem to have left the web, see if you can find a matching Web Archive at The Internet Archive and provide links there instead.

As for cashmusic if it's the same social media it's likely the same place, but if you can't find the old links on the new site, then the Internet Archive might still have the content in a snapshot there?

**Comment by Keerthivardhan1** [comment] 2023-03-20 18:58
hello @possumbilities,
yes I found the snapshot of  url http://creativecommons.cashmusic.org/ --(cashmusic) (in 2016)
<img width="946" alt="cc1122 2" src="https://user-images.githubusercontent.com/110013820/226436375-c5082777-2b25-4fee-9bc3-0adb3e62cec9.png">
I think it should be the right one.
It also has snapshots in 2015.
can you suggest me which one would be the best to replace the broken url?

coming to layervault
 Internet Archive has snapshots but none of them have content in it thay had only the landing page (home page ).
 and for url [https://layervault.com/creative-commons](https://layervault.com/creative-commons/Public%20Domain%20guide)
 it has 2 to 3 snapshots but only one as content in it. and that too the one snapshot has only html content and when we click in a link present in it. that is taking to a blank page.
 here are the screenshots: - 

this the html content shown:-
<img width="757" alt="htmloflay" src="https://user-images.githubusercontent.com/110013820/226438325-06a8ebf1-2f4e-4aa8-b14b-d3bdd971128a.png">

 
suppose if we click on six-licenses-guide this is the result: -

<img width="820" alt="ifweclick" src="https://user-images.githubusercontent.com/110013820/226438366-37808cc2-4339-4971-ab6a-7c0156828ccd.png">

what shell I do @possumbilities ?

**Comment by Keerthivardhan1** [comment] 2023-03-20 19:00
@possumbilities can you please review this issue (decent amount of work is done on it and now it is ready to rise PR)
https://github.com/creativecommons/cc-resource-archive/issues/50 . thanks a lot for your time.

**Comment by possumbilities** [comment] 2023-03-20 19:53
I looked into layervault and it seems this was OUR hosted account there, and the Internet Archive lacks a snapshot of the content, so there'd be no way to repair that particular link-out. 

Feel free to go ahead with a PR for all of the above.

**Comment by Keerthivardhan1** [comment] 2023-03-20 22:10
Since the link cannot be repaired, it would be more efficient to remove it from the code, as broken links can negatively impact search engine optimization.
shell I remove links related to layervault website?

**Comment by Keerthivardhan1** [comment] 2023-03-21 12:58
Everything is almost done, but I have two doubts.
in page of -->get-cc-savvy   links in that page point to 
<img width="719" alt="getccsayb" src="https://user-images.githubusercontent.com/110013820/226610119-b27514e6-8cdb-4fbb-8bac-964a893feb38.png"> (404 error)
However, this page is critical to Creative Commons as it assists individuals and organizations in learning about Creative Commons licenses and how to use them. 
My idea is that we can point all those link to https://creativecommons.org/get-cc-savvy/.
can I Proseed with this. 

********2 . Shell I remove all the links related to  layervault ??? 

All other broken links have been fixed.
Thanks a lot for your time @possumbilities.

**Comment by possumbilities** [comment] 2023-03-21 20:11
@Keerthivardhan1 I think that change works! Go head!

**Comment by Keerthivardhan1** [comment] 2023-03-21 20:26
Ok @possumbilities, Thank you.

**Comment by Keerthivardhan1** [comment] 2023-03-21 22:57
All of the broken links have been repaired. Would you kindly review my pull request at https://github.com/creativecommons/cc-resource-archive/pull/96? Additionally, I came across some errors in the HTML code on the resources page and would like to correct them. Should I create a new issue for this or submit a PR related to the errors in the same issue?
Thanks a lot @possumbilities for helping me out in my contribution journey. Thanks you.

**Comment by Keerthivardhan1** [comment] 2023-03-22 07:01
Now I have fixed the errors in all the html files. and it is ready for PR.

**Comment by Keerthivardhan1** [comment] 2023-03-22 07:40
@possumbilities, 
fixed the errors and created a pull request at https://github.com/creativecommons/cc-resource-archive/pull/99#issue-1635212302. Could you kindly review it when you get a chance? Thanks a lot for your time.
sorry if iam wrong.

**Closed** 2023-03-31 19:03 UTC
Labels: 🟨 priority: medium, 🏁 status: ready for work, 🛠 goal: fix, 💻 aspect: code
