### ISSUE TITLE
[Restructuring] Resizing the logo's container

### ISSUE THREAD

**Issue by codegrann** [creativecommons/cc-resource-archive#97] opened 2023-03-22 04:39 UTC
## Problem
The logo's container at the top covers 100% of the viewport.

## Description
A user would accidentally click at the logo's container which spans all the vw width, which may not be intended. This would distract users navigation.
![Screenshot from 2023-03-21 15-45-41](https://user-images.githubusercontent.com/94289940/226803567-51467c1a-ed88-4e1c-8c7e-7b0671a16dbd.png)

## Resolution
To resolve this, I see it a better way to resize the logo's container so that it be relative to the content .
![Screenshot from 2023-03-22 08-11-27](https://user-images.githubusercontent.com/94289940/226807939-2c3c292e-f712-4b4d-89cb-6b4f0a0f26ac.png)

## Implementation
Replace the [ ] with [x] to check the box.
- [x] I would be interested in implementing this feature.

**Comment by codegrann** [comment] 2023-03-22 04:46
Full width spanning will be appealing for smaller screen sizes.

**Comment by possumbilities** [comment] 2023-03-31 20:12
Pretty sure this is a duplicate of #70

**Closed** 2023-03-31 20:13 UTC
Labels: 🟩 priority: low, ⛔️ status: discarded, ✨ goal: improvement, 💻 aspect: code

**Comment by codegrann** [comment] 2023-03-31 20:18
Acknowledged

**Comment by codegrann** [comment] 2023-03-31 20:31
I would be as willing to help with any issue on the same.
