### ISSUE TITLE
New Design Implementation

### ISSUE THREAD

**Issue by Arpitchugh** [creativecommons/cc-resource-archive#133] opened 2023-03-31 00:19 UTC
## Problem
The CC Resource Archive currently has an outdated visual setup and requires functionality fixes and improvements to enhance the overall user experience.
 
## Description
As per the GSOC idea to update the design of web page, I came up with two design and would like to know of suggestions and any improvements.

1. Taking reference from the main website and using a grid layout: 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/63435960/228991710-f9c55ac0-d954-40f5-9c48-513096a16667.png">

2. Using a Card layout, where content is divided into featured section and rest of the cards will have vertical scroll: 
<img width="671" alt="image" src="https://user-images.githubusercontent.com/63435960/228991881-8af2e234-f37e-49bd-b450-94aca9d496a1.png">

## Features

1. Search bar
2. Improved filter section
3. User can download resource or open codebase directly without visiting a resource first
4. Improved UI

## Additional context
please refer to the Figma design, you can also leave comments there: https://www.figma.com/file/2ijyrOviqLHUyQTQsEVerM/GSOC---CC-resource-archive?node-id=0%3A1&t=mPWLMQINM8Mr0DWf-1

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by Xaid-vfx** [comment] 2023-03-31 06:22
Hey @Arpitchugh,
The above Figma designs are great and much better than the current UI. But the new designs are supposed be in accordance with the Vocabulary UI/UX. All CC websites are expected to have the same UI components which are imported from [Vocabulary](https://cc-vocabulary.netlify.app/?path=/story/hello-wip--page).

**Comment by Arpitchugh** [comment] 2023-03-31 06:33
Hi,
We do have these components in the **Vocabulary** and the above design is built for reference. I would love to add/improve upon any changes that you think could be an issue while using the library.
Also the **grid** design follows the very same grid structure used on the official [CC website](https://creativecommons.org/). 
We can also find reference for **card** design in the [**Vocabulary**](https://cc-vocabulary.netlify.app/?path=/story/layouts-cards--post-vertical) here

**Comment by Xaid-vfx** [comment] 2023-03-31 08:19
About the card design, there are few details missing from the card section. 
As suggested in the [post vertical card](https://cc-vocabulary.netlify.app/?path=/story/layouts-cards--post-vertical) from Vocabulary, you are not supposed to provide **download** and **git** buttons right on top of the card.
It's alright if you designed this just for reference, but the actual implementation should follow designs and components directly from Vocabulary library. 
Good work though, keep contributing 🚀

**Comment by possumbilities** [comment] 2023-03-31 20:21
Likely a duplicate of #72 please move discussion there :)

**Closed by possumbilities** 2023-03-31 20:21 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code
