### ISSUE TITLE
[Feature] Addition of a footer section

### ISSUE THREAD

**Issue by shreyashchandra** [creativecommons/cc-resource-archive#158] opened 2023-04-02 12:18 UTC
## Problem
There is no footer section on the website, which decreases the user experience, the footer will help us to provide some important info and links (like social links, contribution repo links, and contacts...)
![Screenshot (863)](https://user-images.githubusercontent.com/78721024/229350057-38e96fd0-a46c-44f7-aa04-392c98310ae2.png)

## Description
I want to add a simple and clean footer section. Something like this⬇️
![Screenshot (861)](https://user-images.githubusercontent.com/78721024/229350252-96de606d-bf41-496c-b1f1-95761a04ff16.png)

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by justaskulkarni** [comment] 2023-04-02 14:42
Duplicate of #34. It'll be better if the discussion is moved over there.

**Comment by Murdock9803** [comment] 2024-02-29 11:28
This is just same as the issue #34  , So I request @shreyashchandra @possumbilities to close this issue.

**Comment by possumbilities** [comment] 2024-03-01 15:24
Thanks all, closing as duplicate.

**Closed by possumbilities** 2024-03-01 15:24 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code
