### ISSUE TITLE
[Upgrading] Modification in the logo of the website

### ISSUE THREAD

**Issue by ShadyResurrected** [creativecommons/cc-resource-archive#100] opened 2023-03-22 10:33 UTC
## Problem
Previously the user might click on the logo while clicking on the white space present in front of the logo as the display is set to inline for the anchor tag and the image of logo seems to be cut from the bottom as it is not presented properly.

![Screenshot (221)](https://user-images.githubusercontent.com/86824679/226875407-76646a97-b24d-459d-ac35-e2dddb510be8.png)

## Description

The user might face difficulties while navigating the website, plus the logo seems to be not displayed properly.

Look of website after applying this solution:
![Screenshot (219)](https://user-images.githubusercontent.com/86824679/226876578-8c785211-0939-41ca-9974-2834102acf94.png)

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by shreyashchandra** [comment] 2023-03-31 15:36
I would really love to contribute to this issue please trigger this issue so that I would start working on it.

**Comment by possumbilities** [comment] 2023-03-31 20:14
I think this is a duplicate of #70

**Closed by possumbilities** 2023-03-31 20:14 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code
