### ISSUE TITLE
[Feature] Changing the UI of whole website

### ISSUE THREAD

**Issue by Vansh-Baghel** [creativecommons/cc-resource-archive#77] opened 2023-03-12 10:33 UTC
## Problem
* The design of website doesn't look appealing

## Description
* We must improve the website design and UI.
* Include all these lists into smooth dropdown navbar.
![image](https://user-images.githubusercontent.com/103327712/224538890-bfee23a0-db8d-44c5-bc3c-76e0d967206e.png)
* Must add footer including all the other links, social medias and copyright claims.

## Suggestion for improvement 
* As the site is not completely new, we could replace the code with React.js which will build it faster and in easier way.
* If couldn't shift to React then gotta give styling using pure CSS.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Src0p** [comment] 2023-03-12 17:20
It is a nice Idea , but there are many students/contributors who came to this project from Google summer of code ,In the tech stack description , react wasn't mentioned .
This can cause some problems for others.

**Comment by Vansh-Baghel** [comment] 2023-03-12 17:22
> It is a nice Idea , but there are many students/contributors who came to this project from Google summer of code ,In the tech stack description , react wasn't mentioned . This can cause some problems for others.

I see, Isn't it editable?

**Comment by Src0p** [comment] 2023-03-12 17:26
I am not sure , but maybe no.

**Comment by possumbilities** [comment] 2023-03-20 20:27
Duplicate of #72 I'd suggest moving discussion there.

**Closed by possumbilities** 2023-03-20 20:27 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code
