### ISSUE TITLE
[Feature] Update Navigation Bar

### ISSUE THREAD

**Issue by Ipshita02** [creativecommons/cc-resource-archive#157] opened 2023-04-02 12:17 UTC
## Problem
The current navigation bar on the website is outdated and difficult to use. Users have trouble finding the information they need.

![Screenshot (9)](https://user-images.githubusercontent.com/72136711/229352016-f2a813cf-4a6b-4307-9645-cfec4457761a.png)

## Description
I want to create a new navigation bar that is more modern and user-friendly. The new navigation bar will have a clean, minimalist design and be easy to use on all devices. I will also add a drop-down feature to it. I believe that this feature will improve the user experience on the website.

![Screenshot (4)](https://user-images.githubusercontent.com/72136711/229351472-a9e8e2c9-e79b-4ee3-82c0-103c682fa13a.png)

## Alternatives
A good alternative is to create a side-closing navigation feature.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by justaskulkarni** [comment] 2023-04-02 14:44
Duplicate of #48. It'll be better if the discussion is moved over there.

**Comment by Ipshita02** [comment] 2023-04-09 08:40
Hy @possumbilities I have checked issue #48 and no one working on it, that issue is already closed. So if the issue is available can you please assign it to me, I would love to work on that

**Closed** 2024-09-17 13:32 UTC
Labels: 🟩 priority: low, ⛔️ status: discarded, ✨ goal: improvement, 💻 aspect: code
