### ISSUE TITLE
[Feature] New Design in accordance with CC Vocabulary 

### ISSUE THREAD

**Issue by harshhh11** [creativecommons/cc-resource-archive#138] opened 2023-03-31 15:49 UTC
## Problem
The current CC Resource Archive has an outdated visual setup that doesn't match the overall CC aesthetics.

## Description
![Screenshot 2023-03-31 211806](https://user-images.githubusercontent.com/102225113/229168709-f02eddbd-dad8-4640-8a6f-1f17a7938168.png)

[Figma Design Link](https://www.figma.com/file/6FsE1BtWmqs0VwQ63bPkaA/GSOC-CC?node-id=0-1&t=qwTEJCI5Q7lFJqzT-0)

## Additional context
Please Provide Feedback so I can improve it further 

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment] 2023-03-31 20:22
duplicate of #72 please move suggestions and discussion there :)

**Closed by possumbilities** 2023-03-31 20:22 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code
