### ISSUE TITLE
[Feature] No resources available for some mentioned languages

### ISSUE THREAD

**Issue by nishchay-veer** [creativecommons/cc-resource-archive#80] opened 2023-03-15 08:55 UTC
## Problem
 There are no resources available for some mentioned languages on the home page 

## Description
Based on my understanding of the problem and the user's perspective, I suggest of removal of those languages from the home page which doesn't have any resource mapped to it.  By this feature, we eliminate unnecessary redirection. 
You can see there are no resources available for languages like Hindi(hi), Urdu(Ur), Spanish(es) and Mandarin(cmn). So I suggest to remove those tags for increased clarity It can improve usability, and a better overall user experience.

![issue1 2](https://user-images.githubusercontent.com/99465982/225257368-1a00f6be-8e1e-4b21-aaf4-fd94ed165646.png)

## Alternatives
We can add new resources of the above mentioned languages.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment] 2023-03-31 20:00
@nishchay-veer might be good to double check that there is indeed not a bug occurring here, and that there are resources they just aren't displaying.

**Comment by BalrajDhakad** [comment] 2024-03-01 03:40
I am willing to work on this issue can you please assign it to me

**Comment by possumbilities** [comment] 2024-03-01 15:26
@BalrajDhakad feel free to look into this!

**Comment by BalrajDhakad** [comment] 2024-03-01 16:07
okay thanks for your reply it matters alot @possumbilities

**Comment by BalrajDhakad** [comment] 2024-03-02 14:28
Hey @possumbilities ,
I think we should add at least one resource for each language as I have checked and @nishchay-veer mentioned above that there are only four languages which don't have any resource. (Hindi, Urdu, Spanish and Mandarin).

What do you say

**Comment by BalrajDhakad** [comment] 2024-03-02 15:04
Hey @possumbilities ,
I have solved this issue but I am not able to make a PR because of an existing PR for issue #15 and the PR is #191 can you please review it so that I can have another PR for this issue.

**Closed** 2024-03-12 20:42 UTC
Labels: 🟩 priority: low, 🏁 status: ready for work, ✨ goal: improvement, 💻 aspect: code
